//
//  DeployKeyView.swift
//  Orbital
//
//  Created by Jonathan on 4/15/26.
//

import SwiftData
import SwiftUI

// MARK: - Shared Deploy State

private enum DeployState: Equatable {
    case idle
    case deploying(serverName: String)
    case success(serverName: String)
    case failure(serverName: String, message: String)
}

// MARK: - Deploy Command Builder

private func deployCommand(publicKey: String) -> String {
    // Guards against duplicate entries using grep before appending
    let escaped = publicKey.replacingOccurrences(of: "'", with: "'\\''")
    return """
    KEY='\(escaped)'; \
    mkdir -p ~/.ssh && chmod 700 ~/.ssh && \
    (grep -qF "$KEY" ~/.ssh/authorized_keys 2>/dev/null || echo "$KEY" >> ~/.ssh/authorized_keys) && \
    chmod 600 ~/.ssh/authorized_keys
    """
}

// MARK: - DeployKeyToServerSheet

/// Shown from KeyManagementView. Lets the user pick any saved server and deploys
/// the key using that server's existing credential (password or another stored key).
struct DeployKeyToServerSheet: View {
    let key: StoredKey
    @Environment(SSHService.self) private var sshService
    @Environment(\.dismiss) private var dismiss
    @Query(sort: \Server.name) private var servers: [Server]

    @State private var deployState: DeployState = .idle
    @State private var publicKey: String? = nil
    @State private var unsupportedKey = false

    var body: some View {
        NavigationStack {
            Group {
                if unsupportedKey {
                    unsupportedKeyView
                } else {
                    serverList
                }
            }
            .navigationTitle("Deploy Key")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") { dismiss() }
                }
            }
        }
        .presentationDetents([.medium, .large])
        .task { await loadPublicKey() }
    }

    // MARK: - Server List

    private var serverList: some View {
        List {
            Section {
                keyHeaderRow
            }

            Section {
                if servers.isEmpty {
                    Text("No servers configured.")
                        .foregroundStyle(.secondary)
                        .font(.subheadline)
                } else {
                    ForEach(servers) { server in
                        ServerDeployRow(
                            server: server,
                            deployState: deployState,
                            onDeploy: { await deploy(to: server) }
                        )
                    }
                }
            } header: {
                Text("Select a Server")
            } footer: {
                if case .failure(_, let message) = deployState {
                    Text(message)
                        .foregroundStyle(.red)
                } else {
                    Text("Orbital will connect using the server's saved credential and append the public key to ~/.ssh/authorized_keys.")
                }
            }
        }
    }

    // MARK: - Key Header

    private var keyHeaderRow: some View {
        HStack(spacing: 12) {
            Image(systemName: "key.fill")
                .foregroundStyle(.tint)
                .frame(width: 24)
            VStack(alignment: .leading, spacing: 3) {
                Text(key.name)
                    .font(.headline)
                Text("ssh-ed25519")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }

    // MARK: - Unsupported Key

    private var unsupportedKeyView: some View {
        ContentUnavailableView {
            Label("Cannot Deploy This Key", systemImage: "exclamationmark.lock")
        } description: {
            Text("Key deployment is only supported for keys generated by Orbital. For imported keys, copy the public key manually using the swipe action.")
        }
    }

    // MARK: - Actions

    private func loadPublicKey() async {
        guard let raw = await KeychainService.shared.loadIfPresent(key: key.keychainKey) else {
            unsupportedKey = true
            return
        }
        if let keyString = sshPublicKeyString(fromRawEd25519Seed: raw) {
            publicKey = keyString
        } else {
            unsupportedKey = true
        }
    }

    private func deploy(to server: Server) async {
        guard let publicKey else { return }
        deployState = .deploying(serverName: server.name)
        let command = deployCommand(publicKey: publicKey)
        do {
            _ = try await sshService.runCommand(command, on: server)
            deployState = .success(serverName: server.name)
        } catch {
            deployState = .failure(serverName: server.name, message: error.localizedDescription)
        }
    }
}

// MARK: - ServerDeployRow

private struct ServerDeployRow: View {
    let server: Server
    let deployState: DeployState
    let onDeploy: () async -> Void

    var body: some View {
        HStack(spacing: 12) {
            VStack(alignment: .leading, spacing: 3) {
                Text(server.name)
                    .font(.headline)
                Text("\(server.username)@\(server.host):\(server.port)")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            Spacer()

            trailingContent
        }
        .contentShape(Rectangle())
        .onTapGesture {
            guard !isDeploying else { return }
            Task { await onDeploy() }
        }
    }

    @ViewBuilder
    private var trailingContent: some View {
        switch deployState {
        case .deploying(let name) where name == server.name:
            ProgressView()
                .controlSize(.small)

        case .success(let name) where name == server.name:
            Image(systemName: "checkmark.circle.fill")
                .foregroundStyle(.green)
                .transition(.scale.combined(with: .opacity))

        case .failure(let name, _) where name == server.name:
            Image(systemName: "xmark.circle.fill")
                .foregroundStyle(.red)

        default:
            Image(systemName: "arrow.up.circle")
                .foregroundStyle(.secondary)
        }
    }

    private var isDeploying: Bool {
        if case .deploying = deployState { return true }
        return false
    }

    private var isTargeted: Bool {
        switch deployState {
        case .deploying(let n): return n == server.name
        case .success(let n): return n == server.name
        case .failure(let n, _): return n == server.name
        default: return false
        }
    }
}

// MARK: - AuthorizeKeyOnServerSheet

/// Shown from AddEditServerView when the user selects a stored key in the Private Key
/// auth section. Provides a one-time password prompt to authorize the key on the
/// server whose details are currently in the form — without requiring a prior save.
struct AuthorizeKeyOnServerSheet: View {
    let host: String
    let port: Int
    let username: String
    let keyRef: String

    @Environment(SSHService.self) private var sshService
    @Environment(\.dismiss) private var dismiss

    @State private var password = ""
    @State private var deployState: DeployState = .idle
    @State private var publicKey: String? = nil
    @State private var unsupportedKey = false

    private var canDeploy: Bool {
        !password.isEmpty && publicKey != nil && deployState == .idle
    }

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    HStack {
                        Image(systemName: "network")
                            .foregroundStyle(.secondary)
                            .frame(width: 24)
                        Text("\(username)@\(host):\(port)")
                            .font(.subheadline)
                            .foregroundStyle(.primary)
                    }
                } header: {
                    Text("Target Server")
                }

                if unsupportedKey {
                    Section {
                        Label(
                            "Only Orbital-generated keys can be deployed. For imported keys, copy the public key manually.",
                            systemImage: "exclamationmark.triangle"
                        )
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    }
                } else {
                    Section {
                        SecureField("Password", text: $password)
                            .textContentType(.password)
                    } header: {
                        Text("One-Time Password")
                    } footer: {
                        Text("Used only to authorize the key. Not stored after this operation.")
                    }

                    resultSection
                }
            }
            .navigationTitle("Authorize Key")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    if case .deploying = deployState {
                        ProgressView().controlSize(.small)
                    } else {
                        Button("Authorize") {
                            Task { await authorize() }
                        }
                        .disabled(!canDeploy)
                    }
                }
            }
        }
        .presentationDetents([.medium])
        .task { await loadPublicKey() }
    }

    @ViewBuilder
    private var resultSection: some View {
        switch deployState {
        case .success:
            Section {
                Label("Key authorized successfully.", systemImage: "checkmark.circle.fill")
                    .foregroundStyle(.green)
            }
        case .failure(_, let message):
            Section {
                Label(message, systemImage: "xmark.circle.fill")
                    .foregroundStyle(.red)
                    .font(.caption)
                Button("Try Again") { deployState = .idle }
                    .font(.caption.weight(.semibold))
            }
        default:
            EmptyView()
        }
    }

    // MARK: - Actions

    private func loadPublicKey() async {
        guard let raw = await KeychainService.shared.loadIfPresent(key: keyRef) else {
            unsupportedKey = true
            return
        }
        if let keyString = sshPublicKeyString(fromRawEd25519Seed: raw) {
            publicKey = keyString
        } else {
            unsupportedKey = true
        }
    }

    private func authorize() async {
        guard let publicKey, !password.isEmpty else { return }
        deployState = .deploying(serverName: host)

        let tempRef = "deploy-temp-\(UUID().uuidString)"
        do {
            try await KeychainService.shared.saveString(password, key: tempRef)
        } catch {
            deployState = .failure(serverName: host, message: "Failed to prepare credentials: \(error.localizedDescription)")
            return
        }

        let target = SSHConnectionTarget(
            serverID: UUID(),
            serverName: host,
            host: host,
            port: port,
            username: username,
            authMethod: .password,
            credentialRef: tempRef
        )

        defer {
            Task { try? await KeychainService.shared.delete(key: tempRef) }
        }

        let command = deployCommand(publicKey: publicKey)
        do {
            _ = try await sshService.runCommandOnce(command, onTarget: target)
            deployState = .success(serverName: host)
        } catch {
            deployState = .failure(serverName: host, message: error.localizedDescription)
        }
    }
}
